name: project-env
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.12
  - notebook
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.1
  - pip
  - pip:
      - -r requirements.txt
